apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-backend
  labels:
    app: nodejs-backend
spec:
  replicas: 1  # Start with 1 pod
  selector:
    matchLabels:
      app: nodejs-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nodejs-backend
    spec:
      containers:
      - name: nodejs-backend
        # You need to push your image to Container Registry or Artifact Registry
        image: gcr.io/master-dreamer-460107-v1/backend-clusture-nodejs:latest
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
        - name: NODE_ENV
          value: "production"
        readinessProbe:
          httpGet:
            path: /auth/status
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /auth/status
            port: 5001
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-backend-service
spec:
  selector:
    app: nodejs-backend
  ports:
  - port: 80
    targetPort: 5001
  type: LoadBalancer  # Use LoadBalancer for external access on GCP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-backend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80